### PR TITLE
add "use_uvloop" feature flag

### PR DESCRIPTION
**Pull request by bionicles**
https://uvloop.readthedocs.io/user/index.html

### Description

just tinkering, still gotta propagate from a pool. Totally fine with open source / sharing / permissive license on my end

Relevant: #19

### CODE REVIEW

**Comment by bionicles** [comment]
we can test Process and Pool with this flag enabled

**Comment by bionicles** [comment]
is it possible to add a property to the CoreTest class which would propagate the flag to the individual tests?

then we could just run the CoreTest again with uv_loop=True

**Comment by bionicles** [comment]
ready for review + testing

**Comment by bionicles** [comment]
ah, i screwed up, the Process.run_async method is decorated with @staticmethod and doesn't get 'self' -- can we take it off or should we pass it as an argument?

**Comment by jreese** [comment]
I'm not sure that I want to have this level of targeted support for uvloop. The `Pool` class specifically has an [`initializer`](https://aiomultiprocess.omnilib.dev/en/latest/api.html#aiomultiprocess.Pool) argument that allows passing a function/callable that will be executed after the event loop is created. I'd rather see another generalized option that either runs before event loop is created (that could just import/install uvloop), or that creates and returns the event loop itself. This would be more flexible and allow support for other alternative event loops without needing to add yet another flag.

I'm thinking something that would enable this sort of usage:

```python
import uvloop

async with aiomultiprocess.Pool(loop_initializer=uvloop.new_event_loop):
    ...
```

This could be added to `Process` and just passed through via `Pool.create_worker` similar to what you've already got. However, I don't think it's worth duplicating all the existing tests just to verify that everything works with uvloop. There are a number of cases where I these tests might need to run but uvloop isn't (or can't be) available.

**Comment by GoodiesHQ** [comment]
@jreese I started using aiomultiprocess the other day and was bummed when I couldn't figure out how to use uvloop with it. You just saved me. Very nice, thank you.

I also agree that targetted uvloop support is redundant and unnecessary, though I am always glad to see more people using it xD

**Pull request closed without merging**
